/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  darkMode: "false",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#f1f5f9",
        "primary-container": "#fef3c7",
        "on-primary-fixed-variant": "#92400e",
        "secondary-container": "#f1f5f9",
        "surface-variant": "#f1f5f9",
        "surface-container-highest": "#e2e8f0",
        "surface-container-low": "#f8fafc",
        "on-surface-variant": "#64748b",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#475569",
        "surface-bright": "#ffffff",
        "inverse-primary": "#d97706",
        "on-surface": "#0f172a",
        "on-tertiary-fixed-variant": "#0e7490",
        "secondary-fixed": "#e2e8f0",
        "primary": "#d97706",
        "surface-tint": "#d97706",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#cffafe",
        "outline": "#cbd5e1",
        "inverse-surface": "#1e293b",
        "tertiary-container": "#cffafe",
        "secondary-fixed-dim": "#94a3b8",
        "error": "#dc2626",
        "surface-container": "#f8fafc",
        "on-secondary-fixed": "#1e293b",
        "on-background": "#0f172a",
        "on-error-container": "#991b1b",
        "on-primary-container": "#92400e",
        "surface": "#ffffff",
        "on-primary-fixed": "#451a03",
        "tertiary-fixed-dim": "#22d3ee",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f8fafc",
        "on-tertiary-container": "#164e63",
        "surface-dim": "#f1f5f9",
        "secondary": "#64748b",
        "on-tertiary-fixed": "#083344",
        "primary-fixed": "#fef3c7",
        "on-secondary-container": "#475569",
        "error-container": "#fee2e2",
        "on-secondary": "#ffffff",
        "outline-variant": "#e2e8f0",
        "primary-fixed-dim": "#f59e0b",
        "background": "#f8fafc",
        "tertiary": "#0891b2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "grid-margin": "24px",
        "xl": "32px",
        "md": "16px",
        "base": "4px",
        "xs": "4px",
        "grid-gutter": "16px",
        "lg": "24px"
      },
      fontFamily: {
        "poppins": ["Poppins", "sans-serif"],
        "display": ["Poppins", "sans-serif"],
        "body": ["Poppins", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
